Repository NREL/reV, pull requests merged in 2020-03, with the labels that each got.

#133 Gb/output version
  reV/handlers/outputs.py
Labels: bug, enhancement

#134 add package and properties to outputs
  .github/workflows/publish_to_pypi.yml
  .github/workflows/pull_request_tests.yml
  reV/handlers/outputs.py
Labels: enhancement

#135 Resource updates/refactor
  reV/SAM/econ.py
  reV/econ/econ.py
  reV/generation/generation.py
  reV/handlers/collection.py
  reV/handlers/multi_year.py
  reV/handlers/outputs.py
  reV/handlers/resource.py
  reV/offshore/offshore.py
  reV/rep_profiles/rep_profiles.py
  reV/supply_curve/aggregation.py
  reV/supply_curve/point_summary.py
  tests/test_gen_config.py
  tests/test_handlers_multiyear.py
  tests/test_rep_profiles.py
Labels: enhancement

#137 Allow ExclusionsMask with no exclusions
  reV/config/supply_curve_configs.py
  reV/handlers/exclusions.py
  reV/supply_curve/aggregation.py
  reV/supply_curve/cli_aggregation.py
  reV/supply_curve/exclusions.py
  reV/utilities/execution.py
  reV/version.py
  tests/test_curtailment.py
  tests/test_supply_curve_exclusions.py
Labels: enhancement

#139 add n_gids
  .github/release-drafter.yml
  reV/supply_curve/point_summary.py
Labels: feature, refactor

#140 Bug fix on transmission table parse
  reV/handlers/transmission.py
  reV/supply_curve/supply_curve.py
Labels: bug

#142 Add ResourceDataset Handler
  docs/source/reV/reV.handlers.rev_resource.rst
  reV/SAM/SAM.py
  reV/handlers/__init__.py
  reV/handlers/exclusions.py
  reV/handlers/outputs.py
  reV/handlers/parse_keys.py
  reV/handlers/resource.py
  reV/handlers/rev_resource.py
  reV/version.py
  tests/test_SAM_unit_tests.py
  tests/test_handlers_res_hh.py
  tests/test_handlers_res_invalid.py
  tests/test_handlers_resource.py
  tests/test_sza.py
Labels: feature, refactor

#136 Thermal solar sam
  reV/SAM/SAM.py
  reV/SAM/econ.py
  reV/SAM/generation.py
  reV/config/project_points.py
  reV/generation/generation.py
  reV/handlers/sam_resource.py
  tests/data/SAM/linear_default.json
  tests/data/SAM/linear_profiles.pkl
  tests/data/SAM/swh_default.json
  tests/data/SAM/swh_profiles_2013.pkl
  tests/data/SAM/trough_default.json
  tests/test_gen_linear.py
  tests/test_gen_pv.py
  tests/test_gen_swh.py
  tests/test_gen_trough.py
Labels: feature

#144 init loggers on spawned workers
  reV/utilities/execution.py
  reV/utilities/loggers.py
Labels: bug, feature

#146 Refactor aggregation
  bin/reV-conda-3.7
  examples/full_pipeline_execution/config_pipeline.json
  reV/SAM/generation.py
  reV/__init__.py
  reV/cli.py
  reV/config/curtailment.py
  reV/config/supply_curve_configs.py
  reV/pipeline/pipeline.py
  reV/supply_curve/__init__.py
  reV/supply_curve/aggregation.py
  reV/supply_curve/cli_sc_aggregation.py
  reV/supply_curve/exclusions.py
  reV/supply_curve/point_summary.py
  reV/supply_curve/points.py
  reV/supply_curve/sc_aggregation.py
  reV/supply_curve/supply_curve.py
  reV/supply_curve/tech_mapping.py
  reV/utilities/curtailment.py
  setup.py
  tests/test_curtailment.py
  tests/test_supply_curve_aggregation.py
  tests/test_supply_curve_aggregation_friction.py
  tests/test_supply_curve_offshore.py
  tests/test_supply_curve_points.py
  tests/test_supply_curve_vpd.py
Labels: feature, refactor
