Repository NREL/reV, pull requests merged in 2020-04, with the labels that each got.

#148 Fixed a bug where categorical data aggregation gets set in dataframe …
  reV/supply_curve/aggregation.py
  reV/supply_curve/point_summary.py
  reV/utilities/__init__.py
  reV/utilities/utilities.py
  tests/test_supply_curve_aggregation.py
Labels: bug

#151 Competitive Wind Farm Exclusions
  docs/source/reV/reV.supply_curve.competitive_wind_farms.rst
  docs/source/reV/reV.supply_curve.rst
  reV/config/supply_curve_configs.py
  reV/supply_curve/cli_supply_curve.py
  reV/supply_curve/competitive_wind_farms.py
  reV/supply_curve/supply_curve.py
  reV/version.py
  tests/data/comp_wind_farms/sc_full_downwind.csv
  tests/data/comp_wind_farms/sc_full_upwind.csv
  tests/data/comp_wind_farms/sc_points_downwind.csv
  tests/data/comp_wind_farms/sc_points_upwind.csv
  tests/data/comp_wind_farms/sc_simple_downwind.csv
  tests/data/comp_wind_farms/sc_simple_upwind.csv
  tests/data/comp_wind_farms/wind_dirs.csv
  tests/test_supply_curve_wind_dirs.py
Labels: feature

#152 add loggers to SpawnProcessPool
  reV/generation/generation.py
  reV/offshore/offshore.py
  reV/rep_profiles/rep_profiles.py
  reV/supply_curve/aggregation.py
  reV/supply_curve/sc_aggregation.py
  reV/supply_curve/supply_curve.py
  reV/supply_curve/tech_mapping.py
Labels: bug

#154 add valid_sc_points to get gids for aggregation
  reV/handlers/exclusions.py
  reV/supply_curve/aggregation.py
  reV/supply_curve/points.py
  reV/supply_curve/sc_aggregation.py
Labels: feature

#158 use to_records_array from rex
  reV/handlers/outputs.py
  reV/rep_profiles/rep_profiles.py
  requirements.txt
Labels: refactor
