Repository NREL/reV, pull requests merged in 2020-11, with the labels that each got.

#232 Gb/batch dict
  reV/batch/batch.py
  reV/version.py
  requirements.txt
  tests/data/batch_project_1/config_aggregation.json
  tests/data/batch_project_1/config_batch.csv
  tests/test_batch.py
Labels: feature

#233 check gids type in ProjectPoints
  conda.recipe/meta.yaml
  reV/config/project_points.py
  requirements.txt
Labels: bug

#238 Classmethods
  .github/workflows/conda_build.yml
  conda.recipe/meta.yaml
  reV/SAM/SAM.py
  reV/SAM/econ.py
  reV/SAM/generation.py
  reV/batch/batch.py
  reV/config/base_config.py
  reV/config/multi_year.py
  reV/config/project_points.py
  reV/generation/generation.py
  reV/offshore/offshore.py
  reV/offshore/orca.py
  reV/pipeline/pipeline.py
  reV/pipeline/status.py
  reV/qa_qc/qa_qc.py
  reV/rep_profiles/rep_profiles.py
  reV/supply_curve/competitive_wind_farms.py
  reV/supply_curve/exclusions.py
  reV/supply_curve/sc_aggregation.py
  reV/supply_curve/supply_curve.py
  reV/supply_curve/tech_mapping.py
  reV/version.py
  requirements.txt
Labels: refactor

#239 Set exclusion mask dtype to float32
  reV/supply_curve/exclusions.py
  reV/version.py
  tests/test_supply_curve_aggregation_friction.py
  tests/test_supply_curve_exclusions.py
Labels: bug
