Repository NREL/reV, pull requests merged in 2020-05, with the labels that each got.

#162 Mean res refactor
  reV/SAM/SAM.py
  reV/SAM/generation.py
  reV/utilities/curtailment.py
  reV/version.py
  requirements.txt
  tests/test_curtailment.py
Labels: bug

#166 Gb/qa pipeline
  examples/full_pipeline_execution/config_pipeline.json
  examples/full_pipeline_execution/config_qa-qc.json
  reV/cli.py
  reV/config/qa_qc_config.py
  reV/pipeline/pipeline.py
  reV/qa_qc/cli_qa_qc.py
  reV/qa_qc/qa_qc.py
  reV/qa_qc/summary.py
Labels: refactor

#163 QA/QC
  .github/workflows/conda_build.yml
  .github/workflows/pull_request_tests.yml
  .gitignore
  README.rst
  conda.recipe/meta.yaml
  conda_build.sh
  docs/source/reV/reV.qa_qc.cli_qa_qc.rst
  docs/source/reV/reV.qa_qc.qa_qc.rst
  docs/source/reV/reV.qa_qc.rst
  docs/source/reV/reV.qa_qc.summary.rst
  docs/source/reV/reV.rst
  docs/source/reV/reV.utilities.cli_dtypes.rst
  docs/source/reV/reV.utilities.rst
  examples/full_pipeline_execution/config_pipeline.json
  examples/full_pipeline_execution/config_qa-qc.json
  reV/__init__.py
  reV/batch/cli_batch.py
  reV/cli.py
  reV/config/qa_qc_config.py
  reV/config/supply_curve_configs.py
  reV/econ/cli_econ.py
  reV/generation/cli_gen.py
  reV/handlers/cli_collect.py
  reV/handlers/cli_multi_year.py
  reV/offshore/cli_offshore.py
  reV/pipeline/cli_pipeline.py
  reV/pipeline/pipeline.py
  reV/qa_qc/__init__.py
  reV/qa_qc/cli_qa_qc.py
  reV/qa_qc/qa_qc.py
  reV/qa_qc/summary.py
  reV/rep_profiles/cli_rep_profiles.py
  reV/supply_curve/cli_sc_aggregation.py
  reV/supply_curve/cli_supply_curve.py
  requirements.txt
  setup.py
  tests/data/qa_qc/cf_mean_summary.csv
  tests/data/qa_qc/cf_profile_summary.csv
  tests/data/qa_qc/ri_wind_gen_profiles_2010_summary.csv
  tests/data/qa_qc/sc_full_out_1_summary.csv
  tests/test_gen_config.py
  tests/test_qa_qc_summary.py
Labels: feature

#168 Qa excl
  docs/source/reV/reV.config.qa_qc_config.rst
  docs/source/reV/reV.config.rst
  examples/full_pipeline_execution/config_qa-qc.json
  reV/__init__.py
  reV/config/qa_qc_config.py
  reV/qa_qc/__init__.py
  reV/qa_qc/cli_qa_qc.py
  reV/qa_qc/qa_qc.py
  reV/qa_qc/summary.py
  reV/supply_curve/cli_sc_aggregation.py
  reV/supply_curve/exclusions.py
  tests/test_qa_qc_summary.py
Labels: feature

#173 change exclusions to element-wise-minima
  reV/supply_curve/exclusions.py
  reV/version.py
  tests/test_supply_curve_exclusions.py
Labels: bug
