Repository NREL/reV, pull requests merged in 2021-04, with the labels that each got.

#289 update to pysam 2.2.2
  .github/workflows/codecov.yml
  .github/workflows/conda_build.yml
  .github/workflows/gh_pages.yml
  .github/workflows/publish_to_pypi.yml
  .github/workflows/pull_request_tests.yml
  conda.recipe/meta.yaml
  requirements.txt
  setup.py
Labels: refactor

#297 fix cli version request approach
  reV/batch/cli_batch.py
  reV/cli.py
  reV/config/cli_project_points.py
  reV/econ/cli_econ.py
  reV/generation/cli_gen.py
  reV/handlers/cli_collect.py
  reV/handlers/cli_multi_year.py
  reV/offshore/cli_offshore.py
  reV/pipeline/cli_pipeline.py
  reV/qa_qc/cli_qa_qc.py
  reV/rep_profiles/cli_rep_profiles.py
  reV/supply_curve/cli_sc_aggregation.py
  reV/supply_curve/cli_supply_curve.py
Labels: bug, refactor

#299 Numpy eos
  reV/econ/economies_of_scale.py
  reV/supply_curve/cli_sc_aggregation.py
  tests/test_econ_of_scale.py
Labels: bug
